import test from 'node:test'
import assert from 'node:assert/strict'
import { CITIES, SCENARIOS } from '../src/game/data.js'
import { GameStore } from '../src/game/store.js'
class MemoryStorage{constructor(){this.m=new Map()}getItem(k){return this.m.get(k)??null}setItem(k,v){this.m.set(k,v)}removeItem(k){this.m.delete(k)}}
test('reference map scaffold has 40 cities',()=>assert.equal(CITIES.length,40))
test('initial settings expose 189/200/215 scenarios',()=>assert.deepEqual(SCENARIOS.map((s)=>s.year),[189,200,215]))
test('single player alternates inspection and march months',()=>{const s=new GameStore(new MemoryStorage());s.newGame({scenarioYear:189,humanFactions:['liu']});assert.equal(s.mode,'inspection');s.finishCurrentTurn();assert.equal(s.state.month,2);assert.equal(s.mode,'march')})
test('three human players act in the same month before month advances',()=>{const s=new GameStore(new MemoryStorage());s.newGame({humanFactions:['liu','cao','sun']});assert.equal(s.state.month,1);assert.equal(s.humanFaction,'liu');s.finishCurrentTurn();assert.equal(s.state.month,1);assert.equal(s.humanFaction,'cao');s.finishCurrentTurn();assert.equal(s.state.month,1);assert.equal(s.humanFaction,'sun');s.finishCurrentTurn();assert.equal(s.state.month,2);assert.equal(s.humanFaction,'liu')})
test('inspection category is locked per player for the month',()=>{const s=new GameStore(new MemoryStorage());s.newGame({humanFactions:['liu','cao']});assert.equal(s.lockInspectionCategory('domestic'),true);assert.equal(s.lockInspectionCategory('military'),false);assert.equal(s.inspectionCategoryForActive(),'domestic');s.finishCurrentTurn();assert.equal(s.humanFaction,'cao');assert.equal(s.inspectionCategoryForActive(),null);assert.equal(s.lockInspectionCategory('military'),true)})
test('inspection mutates city state',()=>{const s=new GameStore(new MemoryStorage());s.newGame({humanFactions:['cao']});const before=s.state.cities.xuchang.development;const msg=s.executeInspection('develop','xuchang');assert.match(msg,/開發/);assert.ok(s.state.cities.xuchang.development>before)})
test('march creates enemy conflict after inspection turn',()=>{const s=new GameStore(new MemoryStorage());s.newGame({humanFactions:['cao']});s.finishCurrentTurn();const c=s.planMarch('xuchang','xinye');assert.ok(c);assert.equal(c.target,'xinye')})
test('resolving conflict finishes only the active human turn',()=>{const s=new GameStore(new MemoryStorage());s.newGame({humanFactions:['cao','liu']});s.finishCurrentTurn();s.finishCurrentTurn();assert.equal(s.state.month,2);assert.equal(s.humanFaction,'cao');s.planMarch('xuchang','xinye');s.resolveConflict(false);assert.equal(s.state.month,2);assert.equal(s.humanFaction,'liu')})
test('save/load retains parity setup and command lock state',()=>{const mem=new MemoryStorage();const a=new GameStore(mem);a.newGame({scenarioYear:215,difficulty:'hard',animation:false,textSpeed:'fast',humanFactions:['sun','liu']});a.lockInspectionCategory('military');const b=new GameStore(mem);assert.equal(b.load(),true);assert.equal(b.state.scenarioYear,215);assert.deepEqual(b.state.humanFactions,['sun','liu']);assert.equal(b.inspectionCategoryForActive(),'military')})
