import { COLORS, SERIF } from '../game/constants.js'
import { DIFFICULTIES, FACTIONS, SCENARIOS } from '../game/data.js'
import { mdButton } from '../game/input.js'
const SPEEDS=[['slow','慢'],['normal','普通'],['fast','快']]
export class SetupScene{
  constructor(app){this.app=app;this.focus=0;this.scenario=0;this.difficulty=0;this.animation=0;this.speed=1;this.rulerCursor=0;this.rulers=new Set([0]);this.message=''}
  update(_dt,input){const key=input.consume();if(!key)return;const b=mdButton(key);if(b==='HD'){this.app.toggleHd();return}if(b==='B'){this.app.audio.cancel();this.app.go('title');return}if(b==='START'){this.start();return}if(this.focus<4){if(b==='LEFT'){this.focus=(this.focus+3)%4;this.app.audio.move()}if(b==='RIGHT'){this.focus=(this.focus+1)%4;this.app.audio.move()}if(b==='DOWN'||b==='UP'){const d=b==='DOWN'?1:-1;this.changeTop(d);this.app.audio.move()}if(b==='C'){this.focus=4;this.app.audio.confirm()}if(b==='A'){this.changeTop(1);this.app.audio.confirm()}}else{if(b==='LEFT'){this.rulerCursor=(this.rulerCursor-1+7)%7;this.app.audio.move()}if(b==='RIGHT'){this.rulerCursor=(this.rulerCursor+1)%7;this.app.audio.move()}if(b==='UP'){this.focus=0;this.app.audio.move()}if(b==='A'||b==='C'){this.toggleRuler()}}}
  changeTop(d){if(this.focus===0)this.scenario=(this.scenario+d+SCENARIOS.length)%SCENARIOS.length;if(this.focus===1)this.difficulty=(this.difficulty+d+DIFFICULTIES.length)%DIFFICULTIES.length;if(this.focus===2)this.animation=(this.animation+d+2)%2;if(this.focus===3)this.speed=(this.speed+d+3)%3}
  toggleRuler(){if(this.rulers.has(this.rulerCursor)){if(this.rulers.size>1)this.rulers.delete(this.rulerCursor)}else if(this.rulers.size<3)this.rulers.add(this.rulerCursor);else{this.message='最多可由三位玩家同時擔任君主';this.app.audio.alert();return}this.message='';this.app.audio.confirm()}
  start(){if(!this.rulers.size){this.message='請選擇君主';this.app.audio.alert();return}const selected=[...this.rulers].map((i)=>FACTIONS[i].id);this.app.store.newGame({scenarioYear:SCENARIOS[this.scenario].year,difficulty:DIFFICULTIES[this.difficulty].id,animation:this.animation===0,textSpeed:SPEEDS[this.speed][0],humanFactions:selected});this.app.audio.confirm();this.app.go('strategy')}
  draw(){const r=this.app.r;r.clear('#000');r.ornateFrame(7,7,306,210);r.text('請設定初期條件',160,15,15,'#f3efe4','center','top',SERIF,'600');r.line(10,35,310,35,COLORS.red,2);const xs=[46,118,190,261],widths=[72,72,72,92];const titles=['劇　本','難易度','動畫','表　示'];titles.forEach((t,i)=>{r.line(xs[i]-36,36,xs[i]-36,140,COLORS.red,2);r.text(t,xs[i],46,10,this.focus===i?'#f7f0d5':'#9d9d9d','center')});r.line(307,36,307,140,COLORS.red,2);SCENARIOS.forEach((s,i)=>r.text(`${s.year}年`,46,69+i*28,13,i===this.scenario?COLORS.cyan:'#777','center'));DIFFICULTIES.forEach((d,i)=>r.text(d.label,118,69+i*28,12,i===this.difficulty?COLORS.cyan:'#555','center'));['看','不看'].forEach((v,i)=>r.text(v,190,78+i*35,12,i===this.animation?COLORS.cyan:'#555','center'));SPEEDS.forEach((v,i)=>r.text(v[1],261,67+i*27,11,i===this.speed?COLORS.cyan:'#555','center'));if(this.focus<4)r.selector(xs[this.focus]-33,40,widths[this.focus]-6,96,true);r.line(9,141,311,141,COLORS.red,2);r.text('君　主',160,147,12,this.focus===4?'#f3efe4':'#777','center');const rulerXs=[29,72,114,157,200,243,286];FACTIONS.slice(0,7).forEach((f,i)=>{const selected=this.rulers.has(i);const focused=this.focus===4&&this.rulerCursor===i;r.text(f.ruler,rulerXs[i],172,10,selected?COLORS.cyan:'#666','center');if(focused)r.selector(rulerXs[i]-17,167,34,18,true)});r.text('最多選三位君主 · C移到君主 · Z/C選擇 · START開始',160,197,6,'#9f947b','center');if(this.message)r.text(this.message,160,207,6,'#ff8a7e','center');r.scanlines(.025)}
}
