import { createHash } from 'node:crypto'
import { existsSync, readFileSync } from 'node:fs'
import { extname, join, normalize } from 'node:path'

const manifestPath='public/assets/manifests/asset-manifest.v1.json'
const productionSpecPath='public/assets/manifests/production-spec.v1.json'
const generatedManifestPath='public/assets/generated/generated-assets.v1.json'
const manifest=JSON.parse(readFileSync(manifestPath,'utf8'))
const productionSpec=existsSync(productionSpecPath)
  ? JSON.parse(readFileSync(productionSpecPath,'utf8'))
  : {assets:{}}
const generatedManifest=existsSync(generatedManifestPath)
  ? JSON.parse(readFileSync(generatedManifestPath,'utf8'))
  : {assets:{}}
const allowedStatuses=new Set(['planned','ready','disabled'])
const allowedExtensions=new Set(['.png','.webp'])
const sha256Pattern=/^[a-f0-9]{64}$/
const entries=[]

function visit(value,key=''){
  if(!value||typeof value!=='object')return
  if(typeof value.src==='string'){
    entries.push({key,src:value.src,status:value.status})
    return
  }
  for(const [childKey,child] of Object.entries(value)){
    if(childKey==='version'||childKey==='policy')continue
    visit(child,key?`${key}.${childKey}`:childKey)
  }
}

function pngSize(buffer){
  if(buffer.length<24||buffer.toString('ascii',1,4)!=='PNG')return null
  return {width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)}
}

function webpSize(buffer){
  if(buffer.length<30||buffer.toString('ascii',0,4)!=='RIFF'||buffer.toString('ascii',8,12)!=='WEBP')return null
  const type=buffer.toString('ascii',12,16)
  if(type==='VP8X')return {width:1+buffer.readUIntLE(24,3),height:1+buffer.readUIntLE(27,3)}
  if(type==='VP8 '&&buffer.length>=30)return {width:buffer.readUInt16LE(26)&0x3fff,height:buffer.readUInt16LE(28)&0x3fff}
  if(type==='VP8L'&&buffer.length>=25){
    const bits=buffer.readUInt32LE(21)
    return {width:1+(bits&0x3fff),height:1+((bits>>14)&0x3fff)}
  }
  return null
}

function imageSizeBuffer(buffer,ext){
  if(ext==='.png')return pngSize(buffer)
  if(ext==='.webp')return webpSize(buffer)
  return null
}

function generatedBytes(key,entry){
  const generated=generatedManifest.assets?.[key]
  if(!generated||generated.output!==entry.src||!Array.isArray(generated.parts)||!generated.parts.length)return null
  const encoded=generated.parts.map((part)=>{
    const file=normalize(join('public',part))
    if(!existsSync(file))throw new Error(`${key}: generated source part missing at ${file}`)
    return readFileSync(file,'utf8').trim()
  }).join('')
  const bytes=Buffer.from(encoded,'base64')
  if(generated.byteLength!==undefined&&bytes.length!==generated.byteLength)throw new Error(`${key}: generated byteLength expected ${generated.byteLength}, got ${bytes.length}`)
  const hash=createHash('sha256').update(bytes).digest('hex')
  if(generated.sha256&&hash!==generated.sha256)throw new Error(`${key}: generated sha256 mismatch ${hash}`)
  return bytes
}

visit(manifest)

const failures=[]
const seenSrc=new Map()
for(const entry of entries){
  if(!allowedStatuses.has(entry.status))failures.push(`${entry.key}: invalid status ${entry.status}`)
  if(!entry.src.startsWith('assets/'))failures.push(`${entry.key}: src must be project-relative under assets/`)
  if(entry.src.includes('\\')||entry.src.includes('..')||entry.src.startsWith('/'))failures.push(`${entry.key}: unsafe src ${entry.src}`)
  const ext=extname(entry.src).toLowerCase()
  if(!allowedExtensions.has(ext))failures.push(`${entry.key}: runtime image must be PNG or WebP`)
  if(seenSrc.has(entry.src))failures.push(`${entry.key}: duplicate src also used by ${seenSrc.get(entry.src)}`)
  else seenSrc.set(entry.src,entry.key)

  const spec=productionSpec.assets?.[entry.key]
  if(spec?.target&&spec.target!==entry.src)failures.push(`${entry.key}: production spec target ${spec.target} does not match manifest src ${entry.src}`)

  if(entry.status==='ready'){
    const file=normalize(join('public',entry.src))
    let bytes=null
    try{
      bytes=existsSync(file)?readFileSync(file):generatedBytes(entry.key,entry)
    }catch(error){
      failures.push(error.message)
      continue
    }
    if(!bytes){
      failures.push(`${entry.key}: ready asset missing at ${file} and no valid generated source exists`)
      continue
    }
    const dimensions=imageSizeBuffer(bytes,ext)
    if(!dimensions){
      failures.push(`${entry.key}: could not read image dimensions`)
      continue
    }
    const minimum=spec?.minimumRuntime
    if(minimum&&(dimensions.width<minimum.width||dimensions.height<minimum.height))failures.push(`${entry.key}: ${dimensions.width}x${dimensions.height} is smaller than minimum ${minimum.width}x${minimum.height}`)
  }
}

for(const [key,spec] of Object.entries(productionSpec.assets??{})){
  const entry=entries.find((item)=>item.key===key)
  if(!entry)failures.push(`${key}: production spec has no matching manifest entry`)
  if(spec.sourceGenId!==undefined&&typeof spec.sourceGenId!=='string')failures.push(`${key}: sourceGenId must be a string when present`)
  if(spec.forbiddenBakedUI!==undefined&&!Array.isArray(spec.forbiddenBakedUI))failures.push(`${key}: forbiddenBakedUI must be an array when present`)
  if(spec.integrity!==undefined){
    if(!spec.integrity||typeof spec.integrity!=='object'||Array.isArray(spec.integrity)){
      failures.push(`${key}: integrity must be an object when present`)
    }else{
      if(spec.integrity.byteLength!==undefined&&(!Number.isInteger(spec.integrity.byteLength)||spec.integrity.byteLength<=0))failures.push(`${key}: integrity.byteLength must be a positive integer`)
      if(spec.integrity.sha256!==undefined&&!sha256Pattern.test(spec.integrity.sha256))failures.push(`${key}: integrity.sha256 must be a lowercase SHA-256 hex string`)
    }
  }
}

for(const [key,generated] of Object.entries(generatedManifest.assets??{})){
  const entry=entries.find((item)=>item.key===key)
  if(!entry)failures.push(`${key}: generated asset has no matching runtime manifest entry`)
  if(entry&&generated.output!==entry.src)failures.push(`${key}: generated output ${generated.output} does not match manifest src ${entry.src}`)
  const spec=productionSpec.assets?.[key]
  if(spec?.sourceGenId&&generated.sourceGenId&&spec.sourceGenId!==generated.sourceGenId)failures.push(`${key}: generated sourceGenId does not match production spec`)
  if(spec?.integrity?.byteLength!==undefined&&generated.byteLength!==spec.integrity.byteLength)failures.push(`${key}: generated byteLength ${generated.byteLength} does not match production spec integrity ${spec.integrity.byteLength}`)
  if(spec?.integrity?.sha256&&generated.sha256!==spec.integrity.sha256)failures.push(`${key}: generated sha256 does not match production spec integrity`)
}

if(!entries.length)failures.push('manifest contains no asset entries')
if(failures.length){
  console.error('asset manifest check failed:')
  for(const failure of failures)console.error(`- ${failure}`)
  process.exit(1)
}

const counts=entries.reduce((acc,entry)=>{acc[entry.status]=(acc[entry.status]??0)+1;return acc},{})
console.log(`asset manifest check passed: ${entries.length} entries (${counts.ready??0} ready, ${counts.planned??0} planned, ${counts.disabled??0} disabled); production specs ${Object.keys(productionSpec.assets??{}).length}; generated ${Object.keys(generatedManifest.assets??{}).length}`)
